### ISSUE TITLE
[Suggestion] Position is continuously updated with apparently no filtering (android)

### ISSUE THREAD

**Issue by billthefarmer** [tlserver/flutter_map_location_marker#100]
**Is your feature request related to a problem? Please describe.**

I am developing an app with a map display with overlays showing the current position. While testing it became obvious that the position is being rapidly updated continuously even though the test device is stationary. A similar native app I developed on android requests updates with a delay which slows it down. The snippet of code in  `data_stream_factory.dart`:
```dart
              final subscription =
                  Geolocator.getPositionStream().listen((position) {
                streamController.sink.add(position);
              });
```
does not appear to apply any conditions to the stream.

**Describe the solution you'd like**

According to the `Geolocator.getPositionStream().` API, it is possible to add a distance filter. As the geolocation on devices is unlikely to be more accurate than about 5M, adding a distance filter of say 1M should slow it down considerably, while still tracking a moving device.

**Describe alternatives you've considered**

It is possible to disguise the issue by reducing the precision of the position overlay, but that is only hiding the issue.

**Comment by tlserver** [comment]
Thank you for bringing this to our attention. The `positionStream` used in the `CurrentLocationLayer` of the `flutter_map_location_marker` relies on the default behavior of the `Geolocator.getPositionStream()` method, which indeed has a `distanceFilter` set to 0, meaning it will notify the stream for every minor change in position.

To incorporate your requirement for throttling the position updates, you can customize the `positionStream` by specifying a `distanceFilter`. This will ensure that the position updates are only received when the device has moved by the specified distance. You can set the `distanceFilter` to 1 meter or any other value that suits your needs.

Here is how you can provide a custom `positionStream` with a `distanceFilter` to the `CurrentLocationLayer`:

```dart
CurrentLocationLayer(
  positionStream: LocationMarkerDataStreamFactory().fromGeolocatorPositionStream(
    stream: Geolocator.getPositionStream(
      locationSettings: LocationSettings(distanceFilter: 1), // Set the distance filter to 1 meter
    ),
  ),
)
```

Please refer to the [positionStream property documentation](https://pub.dev/documentation/flutter_map_location_marker/latest/flutter_map_location_marker/CurrentLocationLayer/positionStream.html) for further customization.

While we currently have no plans to change the default `distanceFilter` in the `flutter_map_location_marker` package, your feedback is valuable, and we'll consider it for future updates. Meanwhile, the solution above should address your concern by reducing the frequency of position updates when the device is stationary.
