### ISSUE TITLE
[Minor] When location services are disabled, refusing activation via pop-up is asked twice.

### ISSUE THREAD

**Issue by Nico04** [tlserver/flutter_map_location_marker#102]
On Android (tested on 13)

**Describe the bug**
When location services are disabled, refusing activation via pop-up is asked twice.

**To Reproduce**
1. Disable location services in Android's settings.
2. Open app on page where the location marker is used.
3. Pop-up shows-up asking for location permission, accept.
4. Pop-up shows-up asking to enable Google's location service, tap "No thanks".
5. The same pop-up pops again, for no reason, refuse.
6. No more pop-ups, you have normal access to the map.

**Expected behavior**
Location service pop-up should NOT be displayed twice in a row when refusing.

**Smartphone (please complete the following information):**
 - Android (tested on 13)
 - Version 8.0.4
 - Flutter 3.16.9

**Comment by tlserver** [comment]
duplicate to #77
