### ISSUE TITLE
 CurrentLocationLayer() without headerstream param triggers app freezing

### ISSUE THREAD

**Issue by Muffin8175** [tlserver/flutter_map_location_marker#110]
**Describe the bug**
App freezes and opens on current_location_layer.dart

**To Reproduce**
1. run you app that uses CurrentLocationLayer() (or at least without headerstream param)
2. wait a bit

**Expected behavior**
Do not freeze

**Screenshots**
<img width="933" alt="Screenshot 2024-02-28 at 14 40 54" src="https://github.com/tlserver/flutter_map_location_marker/assets/110467033/1fdbadf3-a991-43b4-9639-4821c36922a7">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome and Safari

**Smartphone (please complete the following information):**
 Didn't check

**Additional context**

**Comment by tlserver** [comment]
Sorry for late reply. What platform are you using? web? Have you tried to run example project in your environment? Does this problem exist in example project?
