### ISSUE TITLE
CurrentLocationLayer widget number of rebuilds going crazy 1000 rebuilds under a minute 

### ISSUE THREAD

**Issue by MohdSaadi** [tlserver/flutter_map_location_marker#123]
When adding the CurrentLocationLayer to the flutter map this widget is being rebuild like crazy even when standing still it can reach 4000-6000 + as long the map widget is open 

1. just opening the map page

**Expected behavior**
rebuild only when necessary like on location change or something

**Screenshots**

![Screenshot (250)](https://github.com/user-attachments/assets/ad8b945f-30ad-4c79-9aa7-8478b4e7be89)

 - Device: Pixel 6 API 33
 - OS: Android 13

**Comment by tlserver** [comment]
Thank you for creating the issue. This issue is solved in v9.1.0.

**Comment by MohdSaadi** [comment]
> Thank you for creating the issue. This issue is solved in v9.1.0.

will try it, thank you
