### ISSUE TITLE
Unexpected Console  Bounds print

### ISSUE THREAD

**Issue by xunreal75** [tlserver/flutter_map_location_marker#128]
**Describe the bug**
an unexpected bound print appears and seems not necessary

**To Reproduce**
Create app
start tracking
-> watch the console 
in current_location_layer.dart  Line 538 will a
print([camera.nonRotatedSize, Bounds(sp - r, sp + r)]);

an unexpected console output
flutter: [Point(392.72727272727275, 775.4545454545455), Bounds(Point(46.398952421033755, 46.03468326153234), Point(166.39895242103375, 166.03468326153234))]

**Expected behavior**
don't print this line or make a flag for that behavior

All platforms are affected 
flutter_map_location_marker ^9.1.0

**Comment by xunreal75** [comment]
Same issue  in line 681 with heading --> 
print(heading.heading);

**Comment by tlserver** [comment]
Thanks. Fixed in v9.1.1.
