### ISSUE TITLE
Not correctly centering if map was moving

### ISSUE THREAD

**Issue by RedHappyLlama** [tlserver/flutter_map_location_marker#22]
Hi,

As per https://github.com/tlserver/flutter_map_location_marker/blob/master/example/lib/page/center_fab_example.dart

If the map is moving / scrolling following a user input (swipe and lift), and the user presses the center FAB, the map is not correctly centered.

**Comment by tlserver** [comment]
Yes, this is a known issue, but I cannot find a way to fix it because I cannot find a way to stop the physics simulation for user gesture in flutter map.

**Comment by tlserver** [comment]
It sould be fine when [this PR](https://github.com/fleaflet/flutter_map/pull/1043) land . No fix is needed.
