### ISSUE TITLE
How to toggle navigation

### ISSUE THREAD

**Issue by Farrukh1198** [tlserver/flutter_map_location_marker#23]
How can I toggle navigation mode. If navigation turned on I would like to show marker without rotation at the center of the map, if navigation turned of I would like to show marker with rotation on current location position.

**Comment by tlserver** [comment]
Do you mean that 'hiding heading sector' for 'without rotation'?

You can set [`LocationMarkerLayerOptions.showHeadingSector`](https://pub.dev/documentation/flutter_map_location_marker/latest/flutter_map_location_marker/LocationMarkerLayerOptions/showHeadingSector.html) to false to hide the heading sector.

E.g.
```
      FlutterMap(
        options: MapOptions(
          center: LatLng(0, 0),
          zoom: 1,
          maxZoom: 19,
        ),
        children: [
          TileLayerWidget(
            options: TileLayerOptions(
              urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
              subdomains: ['a', 'b', 'c'],
              maxZoom: 19,
            ),
          ),
          LocationMarkerLayerWidget(
            options: LocationMarkerLayerOptions(
              showHeadingSector: !_navigationMode,
            ),
          ),
        ],
      )
      ```

**Comment by Farrukh1198** [comment]
> Do you mean 'hiding heading sector' for 'without rotation'?
> 
> You can set [`LocationMarkerLayerOptions.showHeadingSector`](https://pub.dev/documentation/flutter_map_location_marker/latest/flutter_map_location_marker/LocationMarkerLayerOptions/showHeadingSector.html) to false to hide the heading sector.
> 
> E.g.
> 
> ```
>       FlutterMap(
>         options: MapOptions(
>           center: LatLng(0, 0),
>           zoom: 1,
>           maxZoom: 19,
>         ),
>         children: [
>           TileLayerWidget(
>             options: TileLayerOptions(
>               urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
>               subdomains: ['a', 'b', 'c'],
>               maxZoom: 19,
>             ),
>           ),
>           LocationMarkerLayerWidget(
>             options: LocationMarkerLayerOptions(
>               showHeadingSector: !_navigationMode,
>             ),
>           ),
>         ],
>       )
>       ```
> ```

Not exactly what I meant. When navigation mode is on, the camera follows the marker in the center. When navigation mode is disabled, the user can explore the map, but the marker will remain at the user's current position.

**Comment by tlserver** [comment]
Version 4.1.0 is ready, in this version, navigation mode can be implemented easily. You may check [this example](https://github.com/tlserver/flutter_map_location_marker/blob/master/example/lib/page/navigation_example.dart).
