### ISSUE TITLE
Custom icon does not rotate with map

### ISSUE THREAD

**Issue by basvdijk** [tlserver/flutter_map_location_marker#24]
I am using a custom marker to show on my location:

```
  LocationMarkerLayerOptions(
    marker: const DefaultLocationMarker(
      color: Colors.blue,
      child: Icon(
        Icons.navigation,
        color: Colors.white,
      ),
    ),
    markerSize: const Size(40, 40),
    markerAnimationDuration: const Duration(
        milliseconds: 100),
  )
```

When I rotate the map with the map controller, the custom Icon stays with the same orientation. It looks like the icon rotates with the map instead of pointing to the direction I am heading.

![screenshot](https://user-images.githubusercontent.com/644550/156661511-06264a44-992f-42e8-804c-70cb183a92de.png)

**Comment by tlserver** [comment]
Um, it is expected behavior. The marker is not for displaying direction.

**Comment by basvdijk** [comment]
> Um, it is expected behavior. The marker is not for displaying direction.

Any thoughts on how I can make it stay pointing to the top independent of the map being rotating?

**Comment by tlserver** [comment]
Not that easy in current version, I will update later and adding support to this usage.

**Comment by basvdijk** [comment]
> Not that easy in current version, I will update later and adding support to this usage.

Would be really appreciated. Makes it a lot clearer to the user where they are driving to. Thanks for your effort for creating and maintaining this plugin!

**Comment by tlserver** [comment]
I am closing this because version 3.1.0 is available now.
