### ISSUE TITLE
Turning off location service on Android API 28 triggers Location access dialog when Marker is built

### ISSUE THREAD

**Issue by aososam** [tlserver/flutter_map_location_marker#26]
If I turn off location service on Android API 28, every time the LocationMarkerLayerWidget is rebuild it triggers a system dialog that says: "For a better experience turn off device location, which uses Google location service", if the dialog showed only once it would be ok but the fact that it is shown everytime the marker builds is a problem because any little change will trigger it.

I am not facing this issue on Android 11.
Library version: 
flutter_map_location_marker: 3.0.2

**Comment by tlserver** [comment]
Sorry, I cannot reproduce this issue. how do you build the map?
