### ISSUE TITLE
Incompatible with flutter_map in github's master branch

### ISSUE THREAD

**Issue by stx** [tlserver/flutter_map_location_marker#28]
**Error: The parameter 'stream' of the method 'LocationMarkerPlugin.createLayer' has type 'Stream<Null>', which does not match the corresponding type, 'Stream<void>', in the overridden method, 'MapPlugin.createLayer'.**

MapPlugin.createLayer now uses Stream<void> instead of Stream<Null>:

https://github.com/fleaflet/flutter_map/blob/master/lib/src/plugins/plugin.dart

**Comment by Sahkay** [comment]
I was able to fix it in my project by changing the references from Stream<Null> to Stream<void> without any issues so far. Should be in lib/src/plugin.dart and lib/src/layer.dart

**Comment by pablojimpas** [comment]
This package depends on the latest published version [`flutter_map: ^0.14.0`](https://github.com/tlserver/flutter_map_location_marker/blob/17d32aacb4fbd48632a38f309d3ae0e3a2a9e594/pubspec.yaml#L13).

Keep an eye on https://github.com/fleaflet/flutter_map/issues/1188 to upgrade this package when a new tagged version is available.
