### ISSUE TITLE
function request : stop listen when enter background

### ISSUE THREAD

**Issue by tsuncp** [tlserver/flutter_map_location_marker#32]
you could add an option to cancel the listener when enter background? 
just like google map, to avoid the blue notifification on the top left corner for ios platform

**Comment by tsuncp** [comment]
```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.resumed:
        _positionStreamSubscription = _subscriptPositionStream();
        break;
      case AppLifecycleState.paused:
        _positionStreamSubscription.cancel();
        break;
      default:
        break;
    }
  }
```

**Comment by tlserver** [comment]
Have you tried to set [showBackgroundLocationIndicator](https://pub.dev/documentation/geolocator_apple/latest/geolocator_apple/AppleSettings/showBackgroundLocationIndicator.html) to false?
