### ISSUE TITLE
Map is not centering

### ISSUE THREAD

**Issue by davideroffo** [tlserver/flutter_map_location_marker#37]
I'm using this package as referenced in the simple guide: https://pub.dev/packages/flutter_map_location_marker#usage

But the map once starts up, is not centered in the user marker.

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FlutterMap(
        mapController: mapController,
        options: MapOptions(
          zoom: 7,
        ),
        children: [
          TileLayerWidget(
            options: TileLayerOptions(
              minZoom: 1,
              maxZoom: 18,
              backgroundColor: Colors.black,
              urlTemplate: 'http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
              subdomains: ['mt0', 'mt1', 'mt2', 'mt3'],
            ),
          ),
          PolygonLayerWidget(
            options: PolygonLayerOptions(
              polygonCulling: false,
              polygons: [
                Polygon(
                  points: [
                    LatLng(currentPosition.latitude + 1,
                        currentPosition.longitude + 1),
                    LatLng(currentPosition.latitude + 4,
                        currentPosition.longitude + 4),
                    LatLng(currentPosition.latitude + 3,
                        currentPosition.longitude + 3),
                  ],
                  color: Colors.blue.withOpacity(0.5),
                ),
              ],
            ),
          ),
          LocationMarkerLayerWidget(),
        ],
      ),
    );
  }
```

am I missing something?

**Comment by tlserver** [comment]
This is the default behaviour. You need to change the centerOnLocationUpdate in LocationMarkerPlugin to `once` or `always` yourself. 
```
LocationMarkerLayerWidget(
  plugin: LocationMarkerPlugin(
    centerOnLocationUpdate: CenterOnLocationUpdate.once,
  ),
),
```
See [document](https://pub.dev/documentation/flutter_map_location_marker/latest/flutter_map_location_marker/LocationMarkerPlugin/centerOnLocationUpdate.html) and [this example](https://github.com/tlserver/flutter_map_location_marker/blob/master/example/lib/page/center_fab_example.dart) if you need a FAB button for centering.

PS. This issue page in github is for reporting bugs or requesting new feature. If you have 'how to use' question, better ask in Stackover Flow or in the flutter map Discord channel.
