### ISSUE TITLE
Is geolocator plugin required ?

### ISSUE THREAD

**Issue by fvisticot** [tlserver/flutter_map_location_marker#38]
Some applications does not use geolocator plugin but location plugin.
Is it possible to "abstract" the location stream to be more flexible on the location plugin to be used ?

**Comment by tlserver** [comment]
Just provide your own [`positionStream`](https://pub.dev/documentation/flutter_map_location_marker/latest/flutter_map_location_marker/LocationMarkerLayerOptions/positionStream.html) in `LocationMarkerLayerOptions`.

Also see the example 5 in README.
[Custom Stream](https://github.com/tlserver/flutter_map_location_marker/blob/master/example/lib/page/custom_stream_example.dart) : Use your own stream, such as position stream from other library or predefined route, as the source.
