### ISSUE TITLE
windows desktop support

### ISSUE THREAD

**Issue by barbalex** [tlserver/flutter_map_location_marker#4]
Would love to see that

**Comment by tlserver** [comment]
I cannot find any location plugin for flutter which support mobile (Android, iOS) and desktop(Windows, mac OS, Linux). The library is currently using [geolocator](https://pub.dev/packages/geolocator) which does not support desktop. I also looked at [location](https://pub.dev/packages/location) but it only support mac OS, mobile and web.

**Comment by barbalex** [comment]
My own fault to dab with beta features...
