### ISSUE TITLE
freezed wrong heading on device without compass sensor

### ISSUE THREAD

**Issue by hallelk** [tlserver/flutter_map_location_marker#40]
when using a device without compass sensor (eg. Xiaomi redmi 9a), the heading appears but it's naturally wrong and stuck. i wasn't able to debug it yet but i would guess it has to do with 
data_stream_factory.dart(38)
`return (stream ?? (!kIsWeb ? FlutterCompass.events! : const Stream.empty()))`
(maybe FlutterCompass.events is null).

i would say the expected behavior would be not to show the heading in this case.

**Comment by tlserver** [comment]
I think `FlutterCompass.events` is never null. Can you help to test if `FlutterCompass.events` is null on Xiaomi redmi 9a? I do not have that phone.

**Comment by hallelk** [comment]
I don't have this phone either. got this feedback from a client. i will try to find a way to reproduce. 
but meanwhile, i got this from [pub.dev](https://pub.dev/packages/flutter_compass)  -
`Note: Android Only: null is returned as direction on android when no sensor available.`

**Comment by tlserver** [comment]
Yes, but in the code, [event](https://pub.dev/documentation/flutter_compass/latest/flutter_compass/FlutterCompass/events.html) return from Stream.map() which is never null.
