### ISSUE TITLE
The marker does not appear on ios

### ISSUE THREAD

**Issue by giorgi19** [tlserver/flutter_map_location_marker#42]

**Comment by tlserver** [comment]
How do you build the map? Any screenshot?

**Comment by giorgi19** [comment]
When opnening the app location marker mostly does not show,. When show it does not move with you. On android it works properly only GPS is jumping when going to the direction.

FlutterMap(
    children: [
      TileLayerWidget(
        options: TileLayerOptions(
          urlTemplate: 'my tile',
          subdomains: ['a', 'b', 'c'],
        ),
      ),
      LocationMarkerLayerWidget(),
    ],
  );

**Comment by njugh1996** [comment]
I run into same issue and I'm already on release....

**Comment by tlserver** [comment]
Is it a permission problem?

**Comment by giorgi19** [comment]
> No, because it sometimes appears

**Comment by tlserver** [comment]
Why this issue is closed?
