### ISSUE TITLE
flutter_map_location_marker not available with flutter_map V3.0.0

### ISSUE THREAD

**Issue by gri38** [tlserver/flutter_map_location_marker#43]
Hello.
First: congratulation and thank you for your plugin !

I'm trying to use in in an app (let's call it MyApp) and your plugin seems not being compatible with v3.0.0 of flutter map. See message at the end.
Do you plan to update ?
Thanks.

Running "flutter pub get" in MyApp...
Because flutter_map_location_marker 4.1.4 depends on flutter_map ^2.2.0 and no versions of flutter_map_location_marker match >4.1.4 <5.0.0, flutter_map_location_marker ^4.1.4 requires flutter_map ^2.2.0.
So, because MyApp depends on both flutter_map ^3.0.0 and flutter_map_location_marker ^4.1.4, version solving failed.
pub get failed (1; So, because MyApp depends on both flutter_map ^3.0.0 and flutter_map_location_marker ^4.1.4, version solving failed.)

**Comment by tlserver** [comment]
Yes, I just started to bring v3 support yesterday. But still need to test. You can use the pr #39 temporarily for v3 flutter map.

**Comment by gri38** [comment]
Thanks a lot!

Le 2022-09-13 07:17, 6y a écrit :

> Yes, I just started to bring v3 support yesterday. But still need to 
> test. You can use the pr #39 [1] temporarily for v3 flutter map.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/tlserver/flutter_map_location_marker/pull/39
[2] 
https://github.com/tlserver/flutter_map_location_marker/issues/43#issuecomment-1244909670
[3]

**Comment by tijee** [comment]
> #39

Hi, thanks for your work! 👍 👏 

Just for information, do you have a rough idea of when you will release a stable version of your fix?

Cheers

**Comment by andrewames** [comment]
Same boat. Can you please update to support v3 thank you much appreciated

**Comment by KristijanZic** [comment]
Added a #39 dependency from github but got this error message:
```
[my_app] flutter pub get
Running "flutter pub get" in my_app...             
Because every version of flutter_map_location_marker from git depends on flutter_map from git and my_app depends on flutter_map from hosted, flutter_map_location_marker from git is forbidden.
So, because my_app depends on flutter_map_location_marker from git, version solving failed.
pub get failed (1; So, because my_app depends on flutter_map_location_marker from git, version solving failed.)
exit code 1
```

**Comment by dineufeld** [comment]
> Added a #39 dependency from github but got this error message:
> 
> ```
> [my_app] flutter pub get
> Running "flutter pub get" in my_app...             
> Because every version of flutter_map_location_marker from git depends on flutter_map from git and my_app depends on flutter_map from hosted, flutter_map_location_marker from git is forbidden.
> So, because my_app depends on flutter_map_location_marker from git, version solving failed.
> pub get failed (1; So, because my_app depends on flutter_map_location_marker from git, version solving failed.)
> exit code 1
> ```

Same error here

**Comment by KristijanZic** [comment]
> Same error here

No worries, you can use my fork for now:
https://github.com/KristijanZic/flutter_map_location_marker

**Comment by tlserver** [comment]
Version 5 is published. Please also see the changelog to read about migration instructions.
