### ISSUE TITLE
[Question] Is Compass Widget available ?

### ISSUE THREAD

**Issue by fvisticot** [tlserver/flutter_map_location_marker#48]
Is there any Compass widget available to display North ?

![IMG_4DFCEFBE5ECC-1](https://user-images.githubusercontent.com/153679/202921154-998ca675-b01e-4cb2-962b-cc738def92cf.jpeg)

**Comment by tlserver** [comment]
Ummm, current no. What information should this compass widget provide? How compass widget is related to user location or direction?
