### ISSUE TITLE
[Bug] Current position initialize with first positionStream update, which delays widget appear

### ISSUE THREAD

**Issue by Pepslee** [tlserver/flutter_map_location_marker#49]
Layer doesn't build until the positionStream receives the first update.
So if I`m not moving and have an accurate position, the layer doesn't build for a long time, because there are no events in positionStream.

``` dart
  @override
  Widget build(BuildContext context) {
    if (_currentPosition != null) {
      return AnimatedLocationMarkerLayer(
        position: _currentPosition!,
        heading: _currentHeading,
        style: widget.style,
        moveAnimationDuration: widget.moveAnimationDuration,
        moveAnimationCurve: widget.moveAnimationCurve,
        rotateAnimationDuration: widget.rotateAnimationDuration,
        rotateAnimationCurve: widget.rotateAnimationCurve,
      );
    } else {
      return const SizedBox.shrink();
    }
  }
```

`_currentPosition`  initialized by null by default.

So my proposition is to use Future builder with `Geolocator.getCurrentPosition` as future

``` dart

@override
  Widget build(BuildContext context) {
    FutureBuilder(
      future: Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        if (snapshot.data != null) {
          Position position = snapshot.data;
          _currentPosition = LocationMarkerPosition(
            latitude: position.latitude,
            longitude: position.longitude,
            accuracy: position.accuracy,
          );
          return AnimatedLocationMarkerLayer(
            position: _currentPosition!,
            heading: _currentHeading,
            style: widget.style,
            moveAnimationDuration: widget.moveAnimationDuration,
            moveAnimationCurve: widget.moveAnimationCurve,
            rotateAnimationDuration: widget.rotateAnimationDuration,
            rotateAnimationCurve: widget.rotateAnimationCurve,
          );
        } else {
          return const SizedBox.shrink();
        }
      },
    );

  }
```

**Comment by Pepslee** [comment]
Yes, I'm using the default value of positionStream.
Yes, I'm already using location sensors before initializing the map.
I think would be better to use `Geolocator.getCurrentPosition()` instead of `Geolocator.getLastKnownPosition()`  in the patch you suggested. 
`Geolocator.getLastKnownPosition()` does not always work correctly, from my experience.

One more thin, [this pull request](https://github.com/tlserver/flutter_map_location_marker/pull/45/commits/675cd4595277b3218d1078374330b91dbd84b942) seems to solve the problem.

**Comment by tlserver** [comment]
Is seem that there is a bug still does not fixed. So I think `getLastKnownPosition()` maybe better. See also https://github.com/Baseflow/flutter-geolocator/issues/999.

**Comment by Pepslee** [comment]
@tlserver Hi, there one more little problem. When I run app at the first time, map with location marker  build at first, and then  I ask user for location permissions, after approving  location marker doesn't appear at all, until the app restart (location widget rebuild).

**Comment by tlserver** [comment]
> @tlserver Hi, there one more little problem. When I run app at the first time, map with location marker  build at first, and then  I ask user for location permissions, after approving  location marker doesn't appear at all, until the app restart (location widget rebuild).

In which OS, you found this issue?

**Comment by Pepslee** [comment]
@tlserver 
android 10, one plus 5.

**Comment by speeteco** [comment]
> @tlserver Hi, there one more little problem. When I run app at the first time, map with location marker build at first, and then I ask user for location permissions, after approving location marker doesn't appear at all, until the app restart (location widget rebuild).
@tlserver 

Hi, i have the same problem
