### ISSUE TITLE
Not work after permission approving.

### ISSUE THREAD

**Issue by tlserver** [tlserver/flutter_map_location_marker#50]
@tlserver Hi, there one more little problem. When I run app at the first time, map with location marker  build at first, and then  I ask user for location permissions, after approving  location marker doesn't appear at all, until the app restart (location widget rebuild).

_Originally posted by @Pepslee in https://github.com/tlserver/flutter_map_location_marker/issues/49#issuecomment-1332677717_

**Comment by Pepslee** [comment]
The problem is still exists in flutter_map_location_marker: ^5.2.0+2

**Comment by chaos123x** [comment]
Hi! Have the same problem. Can you give an understanding of when is gonna be fix? Or how to work around this issue?

**Comment by tlserver** [comment]
It works on my emulator, in both v5.2.1 and v5.2.0+2. What OS and which version you are using to test? Are you running an example or your own code?
[device-2023-04-01-141424.webm](https://user-images.githubusercontent.com/8895426/229269161-a4272a56-819d-4c26-830b-b9904921058f.webm)
