### ISSUE TITLE
Upgrade versions

### ISSUE THREAD

**Issue by FeofanGreek** [tlserver/flutter_map_location_marker#51]
Good day! When do you plan to switch to version 3 of the maps and upgrade the version of the geolocator?

**Comment by tlserver** [comment]
Isn't it currently depend on v3 flutter_map? I updated dependencies this morning, and it will be released soon.

**Comment by FeofanGreek** [comment]
Thank you Currently not working

**Comment by tlserver** [comment]
What do you mean not working?

**Comment by FeofanGreek** [comment]
Now all right
