### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by RedHappyLlama** [tlserver/flutter_map_location_marker#52]
Hi,

Flutter_Map supports Flutter Web, but seemingly this plug-in does not support Flutter Web? Are there any plans to add in this supportability?

Many thanks!

**Comment by tlserver** [comment]
It already supported web, but pub dev cannot correctly show the web supporting benner.

**Comment by JaffaKetchup** [comment]
@tlserver See https://dart.dev/tools/pub/pubspec#platforms

**Comment by yvs2014** [comment]
Trying to run on the web-platform, it complains on flutter_map_location_marker itself
(if I got it correctly)

``
Error: PlatformException(UNSUPPORTED_OPERATION, getLastKnownPosition is not supported on the web platform., null, null)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/geolocator_web/geolocator_web.dart 70:7                              getLastKnownPosition
packages/geolocator/geolocator.dart 54:35                                     getLastKnownPosition
packages/flutter_map_location_marker/src/data_stream_factory.dart 66:48       <fn>
``

**Comment by yvs2014** [comment]
quick fix by ignoring PlatformException thrown by getLastKnownPosition
https://github.com/yvs2014/flutter_map_location_marker/commit/89e2e180e7073632e64e085240b85a3d0fadd026

not sure if that's enough, but it displays a location marker on map running on the web-platform
