### ISSUE TITLE
Current Location Stream Controller

### ISSUE THREAD

**Issue by yakou32** [tlserver/flutter_map_location_marker#54]
Hello,
Looking at the sample code to follow the current location, there's an issue with the actual update of the user location.

The controller `_followCurrentLocationStreamController = StreamController<double?>();` would not provide a stream of locations.

Is this a placeholder, or do I miss something?

Thank you :)

**Comment by yakou32** [comment]
Indeed, yes :)
I had missed something!
Thank you again for this very useful plugin!

**Comment by jesussmile** [comment]
How do you get the current location ?
