### ISSUE TITLE
Package size too large.

### ISSUE THREAD

**Issue by TristanGrobler** [tlserver/flutter_map_location_marker#55]
Builing an APK before adding the package resulted in 26.4 MB APK. Adding the package to pubspec.yaml, running futter pub get and then building APK resulted in a 60.5 MB APK. Both sizes are for release APK.
![Screenshot 2023-02-10 at 13 39 52](https://user-images.githubusercontent.com/70268395/218083747-fe721cd3-3def-4329-b070-68f1ce0a8307.png)

**Comment by tlserver** [comment]
This is a known issue caused by [hemanthrajv/flutter_compass#92](https://github.com/hemanthrajv/flutter_compass/issues/92). I cannot found any alternative package to replace this package last year. I am planning to write a new package to receive heading angle from the device after June 2023 if this issue and other existing issues are not fixed and there are still no alternative package exist.

**Comment by TristanGrobler** [comment]
Have you tried this?

I just added it to my current project and it only bumped it up less than a mb.

**Comment by tlserver** [comment]
Here is my test result.
![image](https://user-images.githubusercontent.com/8895426/221387893-095d10ab-61d1-4d30-8f97-58ecdeceb944.png)
After adding this plugin the size is not increated too much for release apk.
for the settings of *-16, the minSdkVersion is set to `flutter.minSdkVersion`, and it include flutter_map as dependencies.
for the settings of *-23, the minSdkVersion is set to `23`, and it include flutter_map as dependencies.
for the settings of *-fmlm, the minSdkVersion is set to `23`, and it include flutter_map and this plugin as dependencies.

Steps for my test:
Create a flutter project named fmlm_size.
Paste this code to main.dart:
```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
// import 'package:flutter_map_location_marker/flutter_map_location_marker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Size',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Size"),
      ),
      body: FlutterMap(
        options: MapOptions(
          zoom: 1,
          minZoom: 0,
          maxZoom: 19,
        ),
        children: [
          TileLayer(
            urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            subdomains: const ['a', 'b', 'c'],
            userAgentPackageName:
            'net.tlserver6y.flutter_map_location_marker.example',
            maxZoom: 19,
          ),
          // CurrentLocationLayer(),
        ],
      ),
    );
  }
}
```
Paste this code to pubspec.yaml:
```
name: fmlm_size
description: size
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: any
#  flutter_map_location_marker: any


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
```
Run `pub get`.
Run `flutter build apk` and `flutter build apk --debug`.
Add postfix `-16` to two apks.
Edit `app/build.gradle`, change minSdkVersion from `flutter.minSdkVersion` to `23`.
Add this code to `app/src/main/AndroidManifest.xml` after `<manifest ...>` and before `<application ...>`:
```
   <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
   <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```
Run `flutter build apk` and `flutter build apk --debug`.
Add postfix `-23` to two apks.
Uncomment `import 'package:flutter_map_location_marker/flutter_map_location_marker.dart';
` and `CurrentLocationLayer(),` in `main.dart`.
Uncomment `flutter_map_location_marker: any` in `pubspec.yaml`.
Run `pub get`.
Run `flutter build apk` and `flutter build apk --debug`.
Add postfix `-fmlm` to two apks.

**Comment by TristanGrobler** [comment]
Sweet, that sounds promising then

**Comment by TristanGrobler** [comment]
I am sure you are busy, so don't mean to rush you. Do you perhaps have a time frame for releasing package update?

Thanks

**Comment by tlserver** [comment]
I think the published version is already the most updated version. What do you mean?

**Comment by TristanGrobler** [comment]
Ok maybe I must just retry. The package size was still about 50mb too large
when added to my project. Will let you know.

Thanks again.

**Comment by tlserver** [comment]
How do you get this result? Can you provide details reproduce steps?

**Comment by TristanGrobler** [comment]
Ok I tested it again and it is nice an small now, so it is resolved. Thanks
