### ISSUE TITLE
Dependency On FlutterMap 3.1.0 and 4.0.0-dev

### ISSUE THREAD

**Issue by ibraheemalayan** [tlserver/flutter_map_location_marker#63]
Are there any plans to upgrade the dependency on `flutter_map` to `4.0.0-dev.2` at least on a dev channel ?

**Comment by tlserver** [comment]
Same as v4.0.0-dev.1, see [previous reply](https://github.com/tlserver/flutter_map_location_marker/issues/62#issuecomment-1510384993).
