### ISSUE TITLE
How do I disable mocked location?

### ISSUE THREAD

**Issue by ZamirAmiri** [tlserver/flutter_map_location_marker#67]
Hello the title is my question :-)

**Comment by ZamirAmiri** [comment]
Quick reply, I added a piece of code that allows for disabling location mocking. It looks as followed.

in current_location_layer.dart add
`
final bool? disableMocking; // add this.disableMocking in the constructor.
// change the location stream to
positionStream = positionStream ??
            const LocationMarkerDataStreamFactory()
                .fromGeolocatorPositionStream(
                    disabledMockedLocation: disableMocking ?? false)
`

In data_stream_factory change the function to this:
`
 Stream<LocationMarkerPosition?> fromGeolocatorPositionStream({
    Stream<Position?>? stream,
    bool disabledMockedLocation = false,
  }) {
    return (stream ?? defaultPositionStreamSource()).map((Position? position) {
      return position != null && (disabledMockedLocation && !position.isMocked)
          ? LocationMarkerPosition(
              latitude: position.latitude,
              longitude: position.longitude,
              accuracy: position.accuracy,
            )
          : null;
    });
  }
`

**Comment by tlserver** [comment]
As you said this requirement can be fulfilled by providing a filtered position stream. Not plan to change the library.
