### ISSUE TITLE
flutter_compass deprecation warning

### ISSUE THREAD

**Issue by abdlulu** [tlserver/flutter_map_location_marker#7]
Each time I run flutter pub get or run my application which depends on flutter_compass only through this plugin, I get the following warning:

"The plugin `flutter_compass` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration."

**Comment by barbalex** [comment]
flutter_compass has published version 0.7.0 which solves the issue. So need to update the dependency

**Comment by tlserver** [comment]
Thanks you for reminder! Updated dependencies.
