### ISSUE TITLE
Live Location is updating after every 2 sec while in Driving Mode

### ISSUE THREAD

**Issue by Jaymistry26** [tlserver/flutter_map_location_marker#73]
Live Location is updating after every 2 sec while in Driving Mode.

FlutterMap(
      options: MapOptions(
        center: const LatLng(0, 0),
        zoom: 1,
        maxZoom: 19,
      ),
      children: [
        TileLayer(
          urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
          subdomains: const ['a', 'b', 'c'],
          maxZoom: 19,
        ),
        CurrentLocationLayer(),
      ],
    )

**Comment by Jaymistry26** [comment]
yes i tried with different positionStream values, but with high Accuracy as well it's taking 2 sec to update live location while Driving

**Comment by tlserver** [comment]
Is it a problem from `geolocation` package? If yes, please create a issue in that package since `geolocation` is just a default implementation but not neccessary to this package.
