### ISSUE TITLE
Current Location marker isnt show again

### ISSUE THREAD

**Issue by NaufalRizqullah** [tlserver/flutter_map_location_marker#76]
Hello @tlserver , 
before that thank you for this plugin, so awesome.

currently i create (page; called **Page_1**) map to get current location, following you guide on [Floating Action Button to Follow Current Location](https://github.com/tlserver/flutter_map_location_marker/blob/master/example/lib/page/follow_fab_example.dart).

i have another page (Called **Page_2**), when i move that to **Page_2** and back again to **Page_1** i cant get current location, event after click fab button doesnt show any my location.

can u help me? (later if u want ill provide some code if neede)

Thank you.

Best Regard.

NB: but if use [No Stream](https://github.com/tlserver/flutter_map_location_marker/blob/master/example/lib/page/no_stream_example.dart) it work, but i want use Follow FAB cause can following location (and also zooming map). if possilbe can use No Steam, but with addition zooming map on current location?

**Comment by tlserver** [comment]
Sorry, I cannot reproduce the issue from your project.
Here is the screen recording.

https://github.com/tlserver/flutter_map_location_marker/assets/8895426/df549814-e1e3-4492-b2f5-ec395dc719f2

**Comment by NaufalRizqullah** [comment]
Gosh, I was wrong, it's true that mobile devices are safe. (I tried it in webisite mode, so the bug appears, if you try to go back and forth the page then I think it will happen; but its okay i only focus on mobile device). Sorry to bother you, thanks @tlserver  for the clarification. I will close this section. 

Thanks again.
