### ISSUE TITLE
Turn on location dialog is opened multiple times

### ISSUE THREAD

**Issue by froz3nice** [tlserver/flutter_map_location_marker#77]
When device's gps is turned off, this library prompts a dialog to turn on location like google maps. When user presses No thanks, it continues to prompt multiple dialogs on top of eachother. Is there any way to get the callback when user presses "no thanks"? Or is there another way to stop location dialog spamming?

**Comment by tlserver** [comment]
I can reproduce this issue on Android. It seem that this issue is caused by a dependent package. Which platfrom are you using?

**Comment by froz3nice** [comment]
Yes i can reproduce in android, didn't try on ios

**Comment by froz3nice** [comment]
Did you discover which dependent package is causing the issue?

**Comment by tlserver** [comment]
I think it is from 'geolocation'.
