### ISSUE TITLE
Erro when use geolocator 10

### ISSUE THREAD

**Issue by felipeparente** [tlserver/flutter_map_location_marker#81]
This lib need to be updated.
I updated the geolocator, and now i receive this message:

Because flutter_map_location_marker 7.0.4 depends on geolocator ^9.0.2 and no versions of flutter_map_location_marker match >7.0.4 <8.0.0, flutter_map_location_marker ^7.0.4 requires geolocator ^9.0.2.

**Comment by tlserver** [comment]
V7.0.5 is published which support geolocator 10.
