### ISSUE TITLE
Error: uses-sdk:minSdkVersion 19 cannot be smaller than version 20 

### ISSUE THREAD

**Issue by jdevo2004** [tlserver/flutter_map_location_marker#83]
I am_ having an error when implementing flutter_map_location_marker in my project. I am following the instructions here: https://pub.dev/packages/flutter_map_location_marker

I have added the depencancy flutter_map_location_marker: any and then imported it without problems.
I have added import 'package:flutter_map_location_marker/flutter_map_location_marker.dart'; without problems
I added CurrentLocationLayer(), under the tile layer without problems.

When I try to run the project there is the following error:

C:\Users\jdevo\henro_helper_real\android\app\src\debug\AndroidManifest.xml Error:
uses-sdk:minSdkVersion 19 cannot be smaller than version 20 declared in library [:flutter_compass] C:\Users\jdevo\henro_helper_real\build\flutter_compass\intermediates\merged_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 19
Suggestion: use a compatible library with a minSdk of at most 19,
or increase this project's minSdk version to at least 20,
or use tools:overrideLibrary="com.hemanthraj.fluttercompass" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

I have tried for some time to troubleshoot this error and have changed the minSdk version but that also causes more errors.  I assume this package does not require me to install the flutter_compass package but just in case I installed the latest flutter_compass but in doing so it just creates new errors. I have not had this type of error happen for other packages so I assume I am not doing anything wrong.

**Comment by tlserver** [comment]
Change the minSdkVersion from `flutter.minSdkVersionin` to `20` in your `android/app/build.gradle` (around line 50) should solve this problem.

**Comment by tlserver** [comment]
If you see "Location Marker Plugin has not been Setup Correctly, Please follow the instructions in the documentation.", that mean your permission in manifest is not setup correctly.
