### ISSUE TITLE
Performance issue, even when permission is refused

### ISSUE THREAD

**Issue by Nico04** [tlserver/flutter_map_location_marker#91]
**Describe the bug**
I'm surprised to see that the CurrentLocationLayer widget makes Flutter's engine refresh frame constantly, which should be quite bad for battery life.
I'm especially surprised that this happens even when permission is refused (plugin should sleep and do nothing in that case).

**To Reproduce**
1. Add CurrentLocationLayer widget to FlutterMap
2. Open app
3. Open Flutter DevTools, Performance tab
4. Open page where the map is
5. Refuse permission (or not)
6. Watch frame redraw

**Expected behavior**
Package should ask for a redraw only when position has changed, like once per second, not more.
And when permission is refused, package should just sleep.

**Desktop (please complete the following information):**
 - Flluter v3.13.9
 - flutter_map: 6.0.1
 - flutter_map_location_marker: 8.0.0

**Smartphone (please complete the following information):**
Android 13 emulator

**Comment by Nico04** [comment]
Thanks for your quick fix, it does fix the performance issue, but now it throws at startup :
```
Unhandled Exception: LateInitializationError: Field '_headingStreamSubscription@115137202' has not been initialized.
_CurrentLocationLayerState._headingStreamSubscription (package:flutter_map_location_marker/src/current_location_layer.dart)
```

You can try with the "Default Stream Exemple" for instance.

**Comment by tlserver** [comment]
I can run all example without any error in my environment. Please provider more information if this exception still occurs. You may create another issue for this.
