### ISSUE TITLE
Null check error in _CurrentLocationLayerState._rotateMarker

### ISSUE THREAD

**Issue by Nico04** [tlserver/flutter_map_location_marker#94]
**Describe the bug**
I've got 45k events of a bug in my app that's in production :

```
Null check operator used on a null value
current_location_layer.dart in _CurrentLocationLayerState._rotateMarker at line 529 within flutter_map_location_marker
In App
current_location_layer.dart in _CurrentLocationLayerState._subscriptHeadingStream.<fn> at line 363 within flutter_map_location_marker
In App
```

**To Reproduce**
Unfortunately I cannot reproduce it myself, but given the precision of the error line, I hope it would be enough for a fix.

**Smartphone (please complete the following information):**
 - flutter_map_location_marker: ^8.0.2

**Comment by tlserver** [comment]
Line 529 in current_location_layer.dart do not have a null-check operator but a null-aware operator, so it should not cause this error. Are you using some special flags to build the app? (such as `--no-sound-null-safety`, just an example, this flag should be already removed)

**Comment by Nico04** [comment]
Well, in previous version of this file, line 529 was `return _moveMapAnimationController!.forward();`
So maybe it's client that used an old package version.
I'll check if it comes back with new version, sorry.

**Comment by Nico04** [comment]
I can confirm issue is still there even using v8.0.2 (I checked the pubspec.lock).
I don't understand why StackTrace refer to old code though...
