### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by Desumond** [tlserver/flutter_map_location_marker#98]
**Describe the bug**
error:
```
Bad state: Stream has already been listened to. 
stack: 
#0      _StreamController._subscribe (dart:async/stream_controller.dart:686)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:836)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:471)
#3      _CurrentLocationLayerState._subscriptFollowCurrentLocationStream(package:flutter_map_location_marker/src/current_location_layer.dart:396)
#4      _CurrentLocationLayerState._subscriptPositionStream.<anonymous closure> (package:flutter_map_location_marker/src/current_location_layer.dart:312)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123)
#9      _MapStream._handleData (dart:async/stream_pipe.dart:218)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#13     _DelayedData.perform (dart:async/stream_impl.dart:515)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

**To Reproduce**
I can't reproduce the issue because it only occurs on 1% of client devices.
My code is a basic example with almost no modifications from navigation_example.dart included in IndexedStack. The map page is always present in the tree until the end of the route. The error disappears after removing the page from the tree.

**Expected behavior**
Works correctly like on most devices.
![2024-01-04_10-31-52](https://github.com/tlserver/flutter_map_location_marker/assets/63116415/a1609b1a-288d-428d-9905-88c3e614dc2c)

**Screenshots**
![map1](https://github.com/tlserver/flutter_map_location_marker/assets/63116415/6491e56d-f076-4a50-92dd-a0a32bc0f911)
![map2](https://github.com/tlserver/flutter_map_location_marker/assets/63116415/942520b6-78bd-4f72-be2f-27bd42502c94)

**Smartphone:**
 - Device: HUAWEI MAR-AL00, Android 10; Xiaomi M2102J20SG, Android 12; Samsung SM-A207M, Android 11; Samsung SM-A307G, Android 11; TECNO BF7, Android 12
 - OS: Android 

**Additional context**
The error occurs every time the device location is updated. Appears a few minutes after location tracking starts. Appears only on some Android devices (about 10 out of 800). Different devices react differently to this problem. Somewhere the map or device location disappears. This is not a gps problem since the data is registered correctly via flutter_background_geolocation package.

**Comment by tlserver** [comment]
If you remove `CurrentLocationLayer` from the widget tree (for example: a toggle button to enable/disable this layer), your `FollowCurrentLocationStream` is disposed and cannot be reused. You need to recreate the stream each time before adding `CurrentLocationLayer` back to widget tree or just use a boardcast stream on page initialized. See also #97

**Comment by flodaniel** [comment]
I also have this issue with a similar stacktrace:
```
I/flutter (23108): runZonedGuarded: Caught error in my root zone: #0      _StreamController._subscribe (dart:async/stream_controller.dart:686:7)
I/flutter (23108): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:836:19)
I/flutter (23108): #2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
I/flutter (23108): #3      ConcatStream._buildController.<anonymous closure>.moveNext (package:rxdart/src/streams/concat.dart:43:41)
I/flutter (23108): #4      _rootRun (dart:async/zone.dart:1391:47)
I/flutter (23108): #5      _CustomZone.run (dart:async/zone.dart:1301:19)
I/flutter (23108): #6      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
I/flutter (23108): #7      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
I/flutter (23108): #8      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
I/flutter (23108): #9      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
I/flutter (23108): #10     _MultiStreamController.closeSync (dart:async/stream_impl.dart:1115:36)
I/flutter (23108): #11     new Stream.fromIterable.<anonymous closure>.next (dart:async/stream.dart:385:24)
I/flutter (23108): #12     _rootRun (dart:async/zone.dart:1399
```

I do NOT use a custom stream, this is how I use the layer:

```
      CurrentLocationLayer(
        alignPositionOnUpdate: AlignOnUpdate.once,
      ),
```

I have the map in a separate page and this only happens after I open the page the second time. So it appears some subscriptions are not fully disposed and recreated.

**Comment by tlserver** [comment]
It seem that the example project does not have this issue. You may try to create a Minimal, Reproducible Example. It helps the debugging process.

**Comment by timautin** [comment]
I had the same error whenever adding / removing a layer to my map and fixed it by adding a key to my CurrentLocationLayer to prevent it being recreated each time:
```
  CurrentLocationLayer(
    key: UniqueKey(),
    alignPositionStream: _alignPositionStreamController.stream,
    alignPositionOnUpdate: _alignPositionOnUpdate,
  )
```

**Comment by jethrocollins** [comment]
> I had the same error whenever adding / removing a layer to my map and fixed it by adding a key to my CurrentLocationLayer to prevent it being recreated each time:
> 
> ```
>   CurrentLocationLayer(
>     key: UniqueKey(),
>     alignPositionStream: _alignPositionStreamController.stream,
>     alignPositionOnUpdate: _alignPositionOnUpdate,
>   )
> ```

Thanks Very much this seems to have fixed my problem
