### ISSUE TITLE
Can't import plugin, missing files?

### ISSUE THREAD

**Issue by coogle** [tlserver/flutter_map_location_marker#99]
**Describe the bug**

When I do:

```
import 'package:flutter_map_location_marker/flutter_map_location_marker.dart';
```

I get:

```
../../.pub-cache/hosted/pub.dev/flutter_map_location_marker-8.0.0-dev.2/lib/src/animated_location_marker_layer.dart:2:8:
Error: Error when reading '../../.pub-cache/hosted/pub.dev/flutter_map-6.1.0/lib/plugin_api.dart': No such file or directory
import 'package:flutter_map/plugin_api.dart';
```

On `flutter_map` v6.1.0 on Flutter Web

**Expected behavior**

No compile errors.

**Comment by tlserver** [comment]
I am unable to reproduce this issue. It appears that you are using v8.0.0-dev.2, which is not the latest version. I recommend upgrading to the latest version of `flutter_map_location_marker` to see if the issue persists.
